# Workflow to manually deploy static content to GitHub Pages
name: Deploy Static Content

on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # You might need this if you perform operations on the repo in this workflow
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact # Ensure this matches the name (or default name) from build.yml
          path: "downloaded_artifact" # Download the artifact to a specific directory

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_path: downloaded_artifact # Point to the downloaded artifact directory
